### PR TITLE
fix several potential vulnerabilities

### PR DESCRIPTION
**Pull request by Young-X**
fixing oob, null pointer deference

### CODE REVIEW

**Comment by Young-X** [comment]
How about the last two commits?

**Comment by Young-X** [comment]
so, line 495 in kwajd.c is not necessary, isn't it? https://github.com/kyz/libmspack/blob/master/libmspack/mspack/kwajd.c#L495

**Comment by kyz** [comment]
Thanks very much for looking for potential vulnerabilities. What's in this patch is already fixed, but please do share any other vulnerabilities you find in future.

**Comment by kyz** [comment]
> so, line 495 in kwajd.c is not necessary, isn't it? https://github.com/kyz/libmspack/blob/master/libmspack/mspack/kwajd.c#L495

Yes, that's correct. It could just be `if (lzh) lzh->sys->free(lzh);`

**Comment by Young-X** [comment]
> 
> 
> > so, line 495 in kwajd.c is not necessary, isn't it? https://github.com/kyz/libmspack/blob/master/libmspack/mspack/kwajd.c#L495
> 
> Yes, that's correct. It could just be `if (lzh) lzh->sys->free(lzh);`

Gotcha. So, for coordinating the code should be changed.

**Pull request closed without merging**
